DP-6646 - Fix TypeError: 'NoneType' object is not callable (#66) (#85)
* DP-6646 - Fix TypeError: 'NoneType' object is not callable (#66)
This happens when a HEAD request is made. Then the action parameter is None
The stacktrace was :

TypeError: 'NoneType' object is not callable
(5 additional frame(s) were not displayed)
...
  File "rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "rest_framework/mixins.py", line 44, in list
    serializer = self.get_serializer(page, many=True)
  File "rest_framework/generics.py", line 112, in get_serializer
    return serializer_class(*args, **kwargs)
Opties

* DP-6646 - Improve handling